parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  es6: true
  browser: true
  commonjs: true
  mocha: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended

plugins:
  - react
